name: Reusable workflow example

on:
  workflow_call:
    inputs:
      some-input:
        required: true
        type: string
      environment:
        required: false
        type: string
        default: dev
    secrets:
      token:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.token }}
        configuration-path: ${{ inputs.some-input }}

    - run: echo "No environment"

    - run: echo ${{ inputs.some-input }}

    - run: echo ${{ vars.whatever_locally }}

    - run: echo ${{ vars.whatever_other_action }}
  dev:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - run: echo ${{ inputs.some-input }}

    - run: echo ${{ vars.whatever_locally }}

    - run: echo ${{ vars.whatever_other_action }}
  prod:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - run: echo ${{ inputs.some-input }}

    - run: echo ${{ vars.whatever_locally }}

    - run: echo ${{ vars.whatever_other_action }}
